import '@/src/styles/globals.css';
import 'react-loading-skeleton/dist/skeleton.css';

import localFont from "next/font/local";

// import {Vazirmatn} from "next/font/google";


// const vazir = Vazirmatn({
//   subsets: ['arabic', 'latin'],
//   display: "swap"
// });

const vazir = localFont({
  src: "../assets/Vazir.woff2",
  display: "swap"
});

export const metadata = {
  title: 'Quiz App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, about }) {
  // throw new Error();
  return (
    <html lang="fa-IR" dir='rtl' className={vazir.className}>
      <body>{children}{about}</body>
    </html>
  )
}
